name: wisatajogja
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf